config/routes.rb
Rails.application.routes.draw do
  resources :graphs
  resources :leads
  get 'home/index'
  

  root 'home#index'

end

app/models/graph.rb
class Graph < ActiveRecord::Base
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	#attr_accessor  :enddate, :startdate
	before_save :calculations

public
	def calculations
		self.responsedaysleft = self.responsedate - Date.today
		self.contractlength = self.enddate - self.startdate
		self.dayrate = self.value / self.contractlength
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_graph, only: [:show, :edit, :update, :destroy]

  # GET /graphs
  # GET /graphs.json
  def index
    @graphs = Graph.all
  end

  # GET /graphs/1
  # GET /graphs/1.json
  def show
  end

  # GET /graphs/new
  def new
    @graph = Graph.new
  end

  # GET /graphs/1/edit
  def edit
  end

  # POST /graphs
  # POST /graphs.json
  def create
    @graph = Graph.new(graph_params)

    respond_to do |format|
      if @graph.save
        format.html { redirect_to @graph, notice: 'Graph was successfully created.' }
        format.json { render :show, status: :created, location: @graph }
      else
        format.html { render :new }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graphs/1
  # PATCH/PUT /graphs/1.json
  def update
    respond_to do |format|
      if @graph.update(graph_params)
        format.html { redirect_to @graph, notice: 'Graph was successfully updated.' }
        format.json { render :show, status: :ok, location: @graph }
      else
        format.html { render :edit }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphs/1
  # DELETE /graphs/1.json
  def destroy
    @graph.destroy
    respond_to do |format|
      format.html { redirect_to graphs_url, notice: 'Graph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graph
      @graph = Graph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graph_params
      params[:graph]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    
    @lead = Lead.new(lead_params)
    respond_to do |format|
      
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update

    respond_to do |format|

    if @lead.update(lead_params)       
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:forename, :surname, :organisation, :value, :responsedate, :responsedaysleft, :startdate, :enddate, :contractlength, :dayrate)
    end
  end
    
  @chart = LazyHighCharts::HighChart.new('graph') do |f|
  f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
  f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
  f.series(:name => "GDP in Billions", :yAxis => 0, :data => [14119, 5068, 4985, 3339, 2656])
  f.series(:name => "Population in Millions", :yAxis => 1, :data => [310, 127, 1340, 81, 65])

  f.yAxis [
    {:title => {:text => "GDP in Billions", :margin => 70} },
    {:title => {:text => "Population in Millions"}, :opposite => true},
  ]

  f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
  f.chart({:defaultSeriesType=>"column"})
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
	def currency
		number_to_currency(lead.value, :unit => "£ ")
	end
	
	#def chart
	#	<%= high_chart("some_id", @chart) %>
	#end
end

app/views/graphs/_form.html.erb
<%= form_for(@graph) do |f| %>
  <% if @graph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graph.errors.count, "error") %> prohibited this graph from being saved:</h2>

      <ul>
      <% @graph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graphs/edit.html.erb
<h1>Editing Graph</h1>

<%= render 'form' %>

<%= link_to 'Show', @graph %> |
<%= link_to 'Back', graphs_path %>

app/views/graphs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Graphs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graphs.each do |graph| %>
      <tr>
        <td><%= link_to 'Show', graph %></td>
        <td><%= link_to 'Edit', edit_graph_path(graph) %></td>
        <td><%= link_to 'Destroy', graph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Graph', new_graph_path %>

app/views/graphs/new.html.erb
<h1>New Graph</h1>

<%= render 'form' %>

<%= link_to 'Back', graphs_path %>

app/views/graphs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_graph_path(@graph) %> |
<%= link_to 'Back', graphs_path %>

app/views/home/index.html.erb
<h1>Allsund Leads Calculator</h1>

<p>I'll be adding a backend to this where we can calculate our sales funnel</p>

<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forename %><br>
    <%= f.text_field :forename %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :organisation %><br>
    <%= f.text_field :organisation %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :responsedate %><br>
    <%= f.date_select :responsedate %>
  </div>
  <div class="field">
    <%= f.label :responsedaysleft %><br>
    <%= f.text_field :responsedaysleft %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :contractlength %><br>
    <%= f.text_field :contractlength %>
  </div>
  <div class="field">
    <%= f.label :dayrate %><br>
    <%= f.text_field :dayrate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/graph.html.erb
<h1>Graph</h1>

data_array_1 = [1, 4, 3, 5, 9]
data_array_2 = [4, 2, 10, 4, 7]

bar_chart = Gchart.new(
            :type => 'bar',
            :size => '600x400',
            :bar_colors => ['000000', '0088FF'],
            :title => "My Title",
            :bg => 'EFEFEF',
            :legend => ['first data set label', 'second data set label'],
            :data => [data_array_1, data_array_2],
            :filename => 'images/bar_chart.png',
            :stacked => false,
            :legend_position => 'bottom',
            :axis_with_labels => [['x'], ['y']],
            :max_value => 15,
            :min_value => 0,
            :axis_labels => [["A|B|C|D|E"]],
            )

bar_chart.file


<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leads</h1>

<table>
  <thead>
    <tr>
      <th>Forename</th>
      <th>Surname</th>
      <th>Organisation</th>
      <th>Value</th>
      <th>Responsedate</th>
      <th>Responsedaysleft</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Contractlength</th>
      <th>Dayrate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.forename %></td>
        <td><%= lead.surname %></td>
        <td><%= lead.organisation %></td>
        <td><%= number_to_currency(lead.value, :unit => "£ ") %></td>
        <td><%= lead.responsedate %></td>
        <td><%= lead.responsedaysleft %></td>
        <td><%= lead.startdate %></td>
        <td><%= lead.enddate %></td>
        <td><%= lead.contractlength %></td>
        <td><%= number_to_currency(lead.dayrate, :unit => "£ ") %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forename:</strong>
  <%= @lead.forename %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @lead.surname %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @lead.organisation %>
</p>

<p>
  <strong>Value:</strong>
  <%= @lead.value %>
</p>

<p>
  <strong>Responsedate:</strong>
  <%= @lead.responsedate %>
</p>

<p>
  <strong>Responsedaysleft:</strong>
  <%= @lead.responsedaysleft %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @lead.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @lead.enddate %>
</p>

<p>
  <strong>Contractlength:</strong>
  <%= @lead.contractlength %>
</p>

<p>
  <strong>Dayrate:</strong>
  <%= @lead.dayrate %>
</p>

<%= high_chart("some_id", @chart) %>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>